Add `createAndRegister` (PHNX-14939)
CenterEdge/CenterEdge.PaytronixApi pull request #10
Opened 2024-06-27 13:12 UTC by JonathanAtCenterEdge

# Motivations
We need `createAndRegister` for account linkage in Webstores

# Modifications
- Add `POST createAndRegister.json` to our spec
- Condense our enrollment tags to just `Enrollment`

2024-07-08 13:50 UTC, brantburnett requested changes

2024-07-08 13:50 UTC, brantburnett commented on openapi/components/responses/createAndRegisterResponse.yaml
This file should technically be in the `schemas` directory, representing a schema for a response body. The `responses` directory is for entire `response` objects, meaning the response information included beneath a particular status code such as found in `unauthorized.yaml`.

This was done incorrectly previously and I've been gradually fixing the invalid cases.

2024-07-09 12:28 UTC, JonathanAtCenterEdge commented on openapi/components/responses/createAndRegisterResponse.yaml
So, `createAndRegisterCardCreatedSuccess.yaml` should be in `/responses`, and `createAndRegisterResponse.yaml` should be in `/schemas`?

2024-07-09 12:35 UTC, brantburnett commented on openapi/components/responses/createAndRegisterResponse.yaml
If you feel that it's worth creating `createAndRegisterCardCreatedSuccess.yaml`, it's also valid for simple, single use cases to leave that where it is, as an embedded definition within the path/operation definition in the `paths` directory.

2024-07-09 13:09 UTC, brantburnett approved these changes

2024-07-09 13:21 UTC, RobRobertsCE approved these changes

2024-07-09 13:34 UTC, JonathanAtCenterEdge commented
/merge

2024-07-09 13:34 UTC, merged